// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
type BindingCode =
  | keyof typeof SYMBOL_MAP
  | 'Abort'
  | 'Again'
  | 'AltLeft'
  | 'AltRight'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'ArrowUp'
  | 'AudioVolumeDown'
  | 'AudioVolumeMute'
  | 'AudioVolumeUp'
  | 'AudioVolumeUp'
  | 'Backquote'
  | 'Backslash'
  | 'Backspace'
  | 'BracketLeft'
  | 'BracketRight'
  | 'BrightnessUp'
  | 'BrowserBack'
  | 'BrowserFavorites'
  | 'BrowserForward'
  | 'BrowserHome'
  | 'BrowserRefresh'
  | 'BrowserSearch'
  | 'BrowserStop'
  | 'CapsLock'
  | 'Comma'
  | 'ContextMenu'
  | 'ControlLeft'
  | 'ControlRight'
  | 'Convert'
  | 'Copy'
  | 'Cut'
  | 'Delete'
  | 'Digit0'
  | 'Digit1'
  | 'Digit2'
  | 'Digit3'
  | 'Digit4'
  | 'Digit5'
  | 'Digit6'
  | 'Digit7'
  | 'Digit8'
  | 'Digit9'
  | 'Eject'
  | 'End'
  | 'Enter'
  | 'Equal'
  | 'Escape'
  | 'F1'
  | 'F2'
  | 'F3'
  | 'F4'
  | 'F5'
  | 'F6'
  | 'F7'
  | 'F8'
  | 'F9'
  | 'F10'
  | 'F11'
  | 'F12'
  | 'F13'
  | 'F14'
  | 'F15'
  | 'F16'
  | 'F17'
  | 'F18'
  | 'F19'
  | 'F20'
  | 'F21'
  | 'F22'
  | 'F23'
  | 'F24'
  | 'Find'
  | 'Fn'
  | 'Help'
  | 'Home'
  | 'Insert'
  | 'IntlBackslash'
  | 'IntlRo'
  | 'IntlYen'
  | 'KanaMode'
  | 'KeyA'
  | 'KeyB'
  | 'KeyC'
  | 'KeyD'
  | 'KeyE'
  | 'KeyF'
  | 'KeyG'
  | 'KeyH'
  | 'KeyI'
  | 'KeyJ'
  | 'KeyK'
  | 'KeyL'
  | 'KeyM'
  | 'KeyN'
  | 'KeyO'
  | 'KeyP'
  | 'KeyQ'
  | 'KeyR'
  | 'KeyS'
  | 'KeyT'
  | 'KeyU'
  | 'KeyV'
  | 'KeyW'
  | 'KeyX'
  | 'KeyY'
  | 'KeyZ'
  | 'Lang1'
  | 'Lang2'
  | 'Lang3'
  | 'Lang4'
  | 'Lang5'
  | 'LaunchApp1'
  | 'LaunchApp2'
  | 'LaunchMail'
  | 'MediaPlayPause'
  | 'MediaSelect'
  | 'MediaStop'
  | 'MediaTrackNext'
  | 'MediaTrackPrevious'
  | 'MetaLeft'
  | 'MetaRight'
  | 'Minus'
  | 'NonConvert'
  | 'NumLock'
  | 'Numpad0'
  | 'Numpad1'
  | 'Numpad2'
  | 'Numpad3'
  | 'Numpad4'
  | 'Numpad5'
  | 'Numpad6'
  | 'Numpad7'
  | 'Numpad8'
  | 'Numpad9'
  | 'NumpadAdd'
  | 'NumpadComma'
  | 'NumpadDecimal'
  | 'NumpadDivide'
  | 'NumpadEnter'
  | 'NumpadEqual'
  | 'NumpadMultiply'
  | 'NumpadParenLeft'
  | 'NumpadParenRight'
  | 'NumpadSubtract'
  | 'OSLeft'
  | 'OSRight'
  | 'Open'
  | 'PageDown'
  | 'PageUp'
  | 'Paste'
  | 'Pause'
  | 'Period'
  | 'Power'
  | 'PrintScreen'
  | 'Props'
  | 'Quote'
  | 'ScrollLock'
  | 'Select'
  | 'Semicolon'
  | 'ShiftLeft'
  | 'ShiftRight'
  | 'Slash'
  | 'Sleep'
  | 'Space'
  | 'Tab'
  | 'Undo'
  | 'VolumeDown'
  | 'VolumeMute'
  | 'VolumeUp'
  | 'WakeUp';

type BindingMeta = keyof typeof MODIFIER_MAP;

export type Binding =
  | ''
  | BindingCode
  | `${BindingMeta}+${BindingCode}`
  | `${BindingMeta}+${BindingMeta}+${BindingCode}`;

export const MODIFIER_MAP = {
  Shift: 'shiftKey',
  Meta: 'metaKey',
  Ctrl: 'ctrlKey',
  Alt: 'altKey',
} as const;

export const SYMBOL_MAP = {
  '0': 'Digit0',
  '1': 'Digit1',
  '2': 'Digit2',
  '3': 'Digit3',
  '4': 'Digit4',
  '5': 'Digit5',
  '6': 'Digit6',
  '7': 'Digit7',
  '8': 'Digit8',
  '9': 'Digit9',
  A: 'KeyA',
  B: 'KeyB',
  C: 'KeyC',
  D: 'KeyD',
  E: 'KeyE',
  F: 'KeyF',
  G: 'KeyG',
  H: 'KeyH',
  I: 'KeyI',
  J: 'KeyJ',
  K: 'KeyK',
  L: 'KeyL',
  M: 'KeyM',
  N: 'KeyN',
  O: 'KeyO',
  P: 'KeyP',
  Q: 'KeyQ',
  R: 'KeyR',
  S: 'KeyS',
  T: 'KeyT',
  U: 'KeyU',
  V: 'KeyV',
  W: 'KeyW',
  X: 'KeyX',
  Y: 'KeyY',
  Z: 'KeyZ',
  ')': 'Digit0',
  '!': 'Digit1',
  '@': 'Digit2',
  '#': 'Digit3',
  $: 'Digit4',
  '%': 'Digit5',
  '^': 'Digit6',
  '&': 'Digit7',
  '*': 'Digit8',
  '(': 'Digit9',
  ' ': 'Space',
  '"': 'Quote',
  "'": 'Quote',
  '=': 'Equal',
  '+': 'Equal',
  ',': 'Comma',
  '<': 'Comma',
  '-': 'Minus',
  _: 'Minus',
  '.': 'Period',
  '>': 'Period',
  '/': 'Slash',
  '?': 'Slash',
  ':': 'Semicolon',
  ';': 'Semicolon',
  '[': 'BracketLeft',
  '{': 'BracketLeft',
  '\\': 'Backslash',
  '|': 'Backslash',
  ']': 'BracketRight',
  '}': 'BracketRight',
  '`': 'Backquote',
  '~': 'Backquote',
} as const;
